spring:
  application:
    name: eventhub-api
  datasource:
    url: jdbc:postgresql://localhost:15432/eventhub-api-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver